announcer:
  slack:
    enabled: false
    webhookUrl: asdfasdfasdf
  email:
    enabled: true
    type: "ses"  # or "smtp", "custom", etc.
    from: "info@giantrooster.tech"
    to:
      - "bilalcaliskan@protonmail.com"
    cc:
      - "jsagredo@protonmail.com"
      - "jsagredo@protonmail.com"
    bcc:
      - "jsagredo@protonmail.com"
    ses:
      region: "us-east-1"
      accessKey: "AKIA3BI3OPS2AH2DLQN6"
      secretKey: "9I9Am88fwZ6k/iNhdRO3jVO/Q1awmternymeS4Yy"
#    smtp:
#      host: "smtp.example.com"
#      port: 587
#      username: "your_smtp_username"
#      password: "your_smtp_password"
storage:
  s3:
    provider: aws
    accessKey: dsddsdssddsf
    secretKey: asdfasdfasdfasdf
    region: us-east-1
    bucketName: asdfasdfadsf
repositories:
#  - name: user1/project1
#    description: sample description
#    url: "https://github.com/user1/project1/"
#    checkIntervalMinutes: 1
  - name: terraform
    description: sample description
    url: "https://github.com/hashicorp/terraform"
    checkIntervalMinutes: 30
  - name: s3-manager
    url: "https://github.com/bilalcaliskan/s3-manager"
    checkIntervalMinutes: 30
