global:
  oneShot: false
  verbose: false
announcer:
  slack:
    enabled: false
    webhookUrl: asdfasdfasdf
    username: "giantrooster"
    iconUrl: "https://avatars.slack-edge.com/2018-03-07/324429893748_0b9b9b9b9b9b9b9b9b9b_512.png"
  email:
    provider: "aws"
    enabled: true
    type: "ses"  # or "smtp", "custom", etc.
    from: "foo@example.com"
    to:
      - "foo2@example.com"
    cc:
      - "foo3@example.com"
      - "foo4@example.com"
    bcc:
      - "foo5@example.com"
    ses:
#      region: "your_region"
#      accessKey: "your_access_key"
#      secretKey: "your_secret_key"
#    smtp:
#      host: "smtp.example.com"
#      port: 587
#      username: "your_smtp_username"
#      password: "your_smtp_password"
storage:
  provider: "aws"
  s3:
#    provider: aws
    accessKey: dsddsdssddsf
    secretKey: asdfasdfasdfasdf
    region: us-east-1
    bucketName: asdfasdfadsf
repositories:
#  - name: user1/project1
#    description: sample description
#    url: "https://github.com/user1/project1/"
#    checkIntervalMinutes: 1
  - name: terraform
    description: sample description
    url: "https://github.com/hashicorp/terraform"
    checkIntervalMinutes: 30
  - name: s3-manager
    url: "https://github.com/bilalcaliskan/s3-manager"
    checkIntervalMinutes: 30
